### ISSUE TITLE
Store larger profiles from Cleopatra in the profile store

### ISSUE THREAD

**Issue by mikeconley** [jrmuizel/profile-store#1]
e10s is having us profile the content process as well, so now we're getting profiles approaching our 10MB limit. I'm not entirely sure where that limit comes from, but I think it's either a processing limit on computing the hash of the file, or a limit on using the old storage API.

If we switch to the Blobstore API to store these profiles, I believe we get 5GB of storage (before we start getting billed), and a 32MB upload cap.

If computing the hash is the piece that's failing, we might be able to compute that in an asynchronous task, and have Cleopatra poll until the hash is calculated.

**Comment by bgirard** [comment]
I think Jeff saw an error specifically about OOM and we think it comes from the compression. Let's wait until Monday where Jeff can share the data that he has from the app engine logs.

**Comment by mikeconley** [comment]
Coming back around to this. Is there anything wrong with attempting to compress the profile client-side before sending it over?

**Comment by jrmuizel** [comment]
No. That's what we'd like to do. The last I looked at this there was an action item for mstange. I don't remember what it was though.

**Comment by luser** [comment]
I asked mconley about this and he noted that Cleopatra is responsible for submitting the profile to the server currently, and since it's an unprivileged webapp it doesn't have easy access to gzip compression, which is unfortunate. It could certainly pull in some gzip.js sort of thing but that sucks. The alternative would be for the profiler addon to provide a pre-gzip'ed copy of the profile when it provides the profile to Cleopatra, which would only be a few lines of code for chrome JS.

**Comment by jrmuizel** [comment]
This was fixed in f9450c332fac0b

**Comment by mikeconley** [comment]
Bugnotes: http://people.mozilla.org/~mconley2/bugnotes/bug-gh-profile-store-1.html
